apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'iot-sensor-app'
        static_configs:
          - targets: ['flask-service.default.svc.cluster.local:80']
      - job_name: 'postgres'
        static_configs:
          - targets: ['db.default.svc.cluster.local:5432']
