apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-sensor-app
  labels:
    app: iot-sensor-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-sensor-app
  template:
    metadata:
      labels:
        app: iot-sensor-app
    spec:
      containers:
        - name: iot-sensor-app
          image: omeravi/iot-sensor-app:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Waiting for DB...";
              until nc -z $DATABASE_HOST $DATABASE_PORT; do
                sleep 2;
              done;
              echo "DB is up, starting app";
              python app.py
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: DATABASE_PORT
            - name: SENSOR_UPDATE_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: SENSOR_UPDATE_INTERVAL
            - name: DATABASE_URL 
              value: postgresql://postgres:mypassword@db:5432/sensors_db
          ports:
            - containerPort: 5000
